service: guardduby
frameworkVersion: ">=1.48.0"

provider:
  name: aws
  stage: dev
  runtime: go1.x
  region: ap-northeast-1


functions:
  slack:
    handler: main
    role: GuardDutyLambda
    timeout: 30
    description: GuardDutyLambda slack notice
    memorySize: 128
    environment:
      SLACKURL: ${opt:slackurl}
      THRESHOLD: 2.0
    events:
      - cloudwatchEvent:
          event:
            source:
              - 'aws.guardduty'
            detail-type:
              - 'GuardDuty Finding'


resources:
  Resources:
    GuardDutyLambda:
      Type: AWS::IAM::Role
      Properties:
        RoleName: GuardDutyLambda
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/IAMReadOnlyAccess
        Policies:
          - PolicyName: GuardDutyLambda
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - "logs:CreateLogGroup"
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"
                  Resource: "*"